const movies = [
  {
    id: 1,
    title: 'Kingsglaive',
    subtitle: 'Final Fantasy XV',
    storyline: "King Regis, who oversees the land of Lucis, commands his army of soldiers to protect the kingdom from the Niflheim empire's plans to steal the sacred crystal.",
    rating: 4.5,
    imagePath: 'images/Kingsglaive_Final_Fantasy_XV.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 2,
    title: 'Final Fantasy',
    subtitle: 'Spirits Within',
    storyline: 'A scientist makes a last stand on Earth with the help of a ragtag team of soldiers against an invasion of alien phantoms.',
    rating: 4.5,
    imagePath: 'images/Final_Fantasy_Spirits_Within.jpg',
    bookmarked: false,
    genre: 'fantasy',
  },
  {
    id: 3,
    title: 'Ghost In The Shell',
    subtitle: 'Ghost In The Shell',
    storyline: 'A hacker known as the Puppet Master is hunted by a female cyborg cop and her partner. This film is a revised version of Ghost in the Shell (1995).',
    rating: 5,
    imagePath: 'images/Ghost_In_The_Shell_2_0.jpg',
    bookmarked: false,
    genre: 'comedy',
  },
  {
    id: 4,
    title: 'Appleseed Alpha',
    subtitle: 'Appleseed Alpha',
    storyline: "A young female soldier Deunan and her cyborg partner Briareos survive through the post World War 3 apocalyptic New York in search of human's future hope, the legendary city of Olympus.",
    rating: 3.8,
    imagePath: 'images/Appleseed_Alpha.jpg',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 5,
    title: 'Resident Evil',
    subtitle: 'Vendetta',
    storyline: 'Chris Redfield enlists the help of Leon S. Kennedy and Rebecca Chambers to stop a death merchant, with a vengeance, from spreading a deadly virus in New York.',
    rating: 4.2,
    imagePath: 'images/Resident_Evil_Vendetta.jpg',
    bookmarked: true,
    genre: 'fantasy',
  },
  {
    id: 6,
    title: 'Arrival',
    subtitle: 'Why Are They Here?',
    storyline: 'Quando seres interplanetários deixam marcas na Terra, a Dra. Louise Banks (Amy Adams), uma linguista especialista no assunto, é procurada por militares para traduzir os sinais e desvendar se os alienígenas representam uma ameaça ou não. No entanto, a resposta para todas as perguntas e mistérios pode ameaçar a vida de Louise e a existência de toda a humanidade.',
    rating: 4.2,
    imagePath: 'images/arrival.jpg',
    bookmarked: true,
    genre: 'sci-Fi',
  },
  {
    id: 7,
    title: 'Schindler\'s List',
    subtitle: 'The List Is Life',
    storyline: 'A inusitada história de Oskar Schindler (Liam Neeson), um sujeito oportunista, sedutor, "armador", simpático, comerciante no mercado negro, mas, acima de tudo, um homem que se relacionava muito bem com o regime nazista, tanto que era membro do próprio Partido Nazista...',
    rating: 3.9,
    imagePath: 'images/Schindler.jpg',
    bookmarked: true,
    genre: 'war',
  },
  {
    id: 8,
    title: 'Enola Holmes',
    subtitle: 'The List Is Life',
    storyline: 'Enola Holmes (Millie Bobby Brown) é uma menina adolescente cujo irmão, 20 anos mais velho, é o renomado detetive Sherlock Holmes (Henry Cavill). Quando sua mãe desaparece, fugindo do confinamento da sociedade vitoriana e deixando dinheiro para trás para que ela faça o mesmo, a menina inicia uma investigação para descobrir o paradeiro dela, ao mesmo tempo em que precisa ir contra os desejos de seu irmão, Mycroft (Sam Claflin), que quer mandá-la para um colégio interno só de meninas.',
    rating: 4.1,
    imagePath: 'images/enola.jpg',
    bookmarked: true,
    genre: 'crime',
  },
  {
    id: 9,
    title: 'Black Panther',
    subtitle: 'Black Panther',
    storyline: 'Em Pantera Negra, após a morte do rei T\'Chaka (John Kani), o príncipe T\'Challa (Chadwick Boseman) retorna a Wakanda para a cerimônia de coroação. Nela são reunidas as cinco tribos que compõem o reino, sendo que uma delas, os Jabari, não apoia o atual governo. T\'Challa logo recebe o apoio de Okoye (Danai Gurira), a chefe da guarda de Wakanda, da irmã Shuri (Letitia Wright), que coordena a área tecnológica do reino, e também de Nakia (Lupita Nyong\'o), a grande paixão do atual Pantera Negra, que não quer se tornar rainha. Juntos, eles estão à procura de Ulysses Klaue (Andy Serkis), que roubou de Wakanda um punhado de vibranium, alguns anos atrás.',
    rating: 4.3,
    imagePath: 'images/black.jpeg',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 10,
    title: 'The Corn Is Green',
    subtitle: 'The Corn Is Green',
    storyline: 'A entusiasmada professora Lilly Moffat (Katharine Hepburn) está determinada a educar crianças pobres e analfabetas em uma comunidade do país de Gales. Ela encontra resistência ao seu projeto no escudeiro local (Bill Fraser) e é desestimulada. Contudo, ela descobre Morgan Evans (Ian Saynor), um brihante estudante com um futuro não tão animador, e decide ajudá-lo a realizar seu potencial.',
    rating: 5.0,
    imagePath: 'images/corn.jpg',
    bookmarked: true,
    genre: 'comedy',
  },
];

export default movies;
